### PR TITLE
chore(deps): bump vitest to v3 (resolves Dependabot alerts)

### PR DESCRIPTION
**Pull request by mindsers**
## Summary

Resolves the two open Dependabot alerts on master by upgrading vitest from `^2.0.0` to `^3.0.0`. Vitest 3 bundles fixed versions of the transitive deps the alerts flagged:

| Alert | Pkg | Was | Now | Fix req |
|---|---|---|---|---|
| GHSA-4w7w-66w2-5vf9 | `vite` | 5.4.21 | 7.3.3 | ≥6.4.2 |
| GHSA-67mh-4wv8-2f99 | `esbuild` | 0.21.5 | 0.27.7 | ≥0.25.0 |

Both vulnerabilities are in dev-server code paths neither used by this repo's CI nor shipped in `dist/index.js` (which is bundled via ncc, not vite/esbuild). The fix is hygiene cleanup, not exposure remediation — but the alerts will keep nagging until resolved.

Stays one major behind vitest 4. Vitest 4 changed how globals types are exposed in a way that breaks the existing `tsconfig.json` wiring (`Cannot find name 'test' / 'expect' / 'AggregateError'` everywhere) — we already reverted a vitest 4 bump for that reason. Vitest 3 keeps the v2 globals shape so the existing `"types": ["node", "vitest/globals"]` continues to work unmodified.

### Verification

- [x] `npx tsc --noEmit` clean.
- [x] `npx vitest run` — 75 tests across 13 suites green under Vitest 3.2.4.
- [x] `npm run build && git diff --exit-code dist/` — no diff.
- [x] `npm ls vite esbuild` — confirms vite@7.3.3 and esbuild@0.27.7 are reachable through the vitest chain.

## Constraints honored

- **No source changes.** Only `package.json` (vitest range) and `package-lock.json` (regenerated).
- **`dist/index.js` unchanged.** Vitest is dev-only; doesn't reach the action runtime.
- **`v2` tag not moved.** This PR doesn't push a tag.
- **No `CHANGELOG.md` Unreleased changes** — internal devDep bump, invisible to consumers.

## Notes for reviewers

- Independent of PR #115 (Phase 4 project metadata) — they touch overlapping lines in `package.json` so whichever merges second will need a trivial rebase. No semantic conflict in either order.
- `npm test` in this PR will fail locally for anyone who has a `.claude/settings.local.json` because Biome's `includes: ["**", "!dist", "!node_modules"]` doesn't exclude `.claude`. That ignore-list fix lives on the Phase 4 branch and will land with that PR. In CI the file doesn't exist, so it's not a CI issue.

### CODE REVIEW

**Comment by mindsers** [comment]
@copilot resolve the merge conflicts in this pull request

**Comment by mindsers** [comment]
Superseded by #118 (comprehensive toolchain upgrade).
